src/app/api/webtoonDetailApi.ts, src/app/api/webtoonsApi.ts, src/entities/webtoondetail/model/store.ts, src/entities/webtoondetail/types.ts, src/pages/webtoon/WebtoonDetail.tsx
=> #14 웹툰 상세피이지 추가

src/app/App.tsx, src/app/api/authApi.tsx, src/app/api/userApi.ts, src/app/routes/index.tsx, src/entities/auth/model/authStore.ts, src/entities/auth/model/types.ts, src/entities/auth/ui/LoginForm.tsx, src/entities/user/model/types.ts, src/entities/user/model/userStore.ts, src/pages/error/Error.tsx, src/pages/user/MyPage.tsx, src/pages/user/userpage/UserComments.tsx, src/pages/user/userpage/UserFollowees.tsx, src/pages/user/userpage/UserFollowers.tsx, src/pages/user/userpage/UserLikeWebtoon.tsx, src/pages/user/userpage/UserProfile.tsx, src/widgets/header/ui/HeaderActions.tsx, src/widgets/layout/ui/Layout.tsx
> 마이페이지 구현 및 에러페이지 추가
- closed #31
- 마이페이지 구현 및 에러페이지 추가
=> 31 feat 마이페이지 api 연동 및 컴포넌트 추가

src/app/routes/AdminProtectedRoute.tsx, src/app/routes/ProtectedRoute.tsx, src/app/routes/index.tsx, src/entities/user/model/types.ts, src/pages/admin/AdminMain.tsx, src/pages/admin/UserManagement.tsx, src/pages/admin/WebtoonManagement.tsx, src/pages/admin/recommendation/FeedbackStatus.tsx, src/pages/admin/settings/TagManagement.tsx, src/pages/admin/user/UserStats.tsx, src/pages/admin/visualization/UserAnalysis.tsx
=> #39 관리자 페이지 UI 구성

src/app/api/webtoonDetailApi.ts, src/features/search/ui/SearchBar.tsx, src/pages/search/Search.tsx
=> #42 웹툰 서치 페이지 구현

src/app/api/webtoonsApi.ts, src/entities/search/model/searchStore.ts, src/entities/search/model/types.ts, src/entities/webtoon/model/store.ts, src/features/search/ui/SearchBar.tsx, src/pages/search/Search.tsx
=> #44 서치 타입 오류

src/app/api/signup.ts, src/app/routes/index.tsx, src/entities/auth/model/signupStore.ts, src/entities/auth/model/types.ts, src/pages/auth/signup/Signup.tsx, src/pages/auth/signup/steps/UserInfo.tsx
- closed #55
- 회원가입 api 연동(db로 데이터 들어가는거 확인)
=> 회원가입 api 연동

package-lock.json, package.json
=> #64 UUID 의존성 추가

src/app/routes/index.tsx, src/pages/auth/signup/steps/UserInfo.tsx
- closed #71
- 라우터 오류 수정, 회원가입 에러 메시지 보이게 변경
=> fix: 라우터 수정 및 회원가입 오류 메시지 보이게 수정

src/pages/admin/stats/UserStats.tsx, src/pages/admin/stats/WebtoonStats.tsx
#76 관리자 페이지 통계 페이지 구현
#76 관리자 페이지 통계 페이지 구현
#76 관리자 페이지 통계 페이지 구현
#76 관리자 페이지 통계 페이지 구현
=> #76 관리자 페이지 통계 페이지 구현

package-lock.json, package.json, src/entities/auth/api/store.ts, src/entities/auth/model/types.ts
=> #86 JWT 토큰 디코딩 기능 구현

src/entities/user/api/userActivityApi.ts, src/pages/user/mypage/BioSection.tsx, src/pages/user/mypage/MyProfile.tsx
=> #95 마이페이지 이미지 에러

src/pages/user/userpage/UserBioSection.tsx, src/pages/user/userpage/UserProfile.tsx
하드코딩된 사용자 객체를 useAuthStore로 대체하여 인증 처리 일관성을 개선함. 사용자 데이터 사용 시 null 체크를 추가해 안전성을 확보했고, 좋아요한 웹툰 리스트의 key 처리 개선 및 bio 데이터 로딩 로직을 명확하게 다듬음."
100 번 :) FIX : 팔로우 로직에 auth store를 통합하여 사용자 프로필 리팩토링.
100 번 :) FIX : 팔로우 로직에 auth store를 통합하여 사용자 프로필 리팩토링.
100 번 :) FIX : 팔로우 로직에 auth store를 통합하여 사용자 프로필 리팩토링.
=> 100 번 :) FIX : 팔로우 로직에 auth store를 통합하여 사용자 프로필 리팩토링.

src/entities/user/api/userActivityApi.ts, src/pages/user/userpage/UserBioSection.tsx, src/pages/user/userpage/UserProfile.tsx
102 Fix/ 유저 페이지 소개 페이지 api 버그수정
=> 102 Fix/ 유저 페이지 소개 페이지 api 버그수정

src/entities/create-id-recom/api/sendWithAuth.ts
=> fix: api 백엔드와 맞게 수정

src/entities/webtoon/api/api.ts, src/entities/webtoon/api/store.ts, src/entities/webtoon/model/types.ts, src/entities/webtoon/ui/WebtoonCard.tsx, src/features/webtoon-list/ui/WebtoonSlider.tsx, src/pages/webtoon/WebtoonMain.tsx, src/widgets/header/ui/Header.tsx
=> #108 웹툰 인기 목록 api 연결

src/entities/user/api/profileStore.ts, src/entities/user/api/useProfileImages.ts, src/entities/webtoondetail/api/webtoonDetailApi.ts, src/entities/webtoondetail/model/store.ts, src/entities/webtoondetail/model/types.ts, src/pages/user/mypage/FolloweesList.tsx, src/pages/user/mypage/FollowersList.tsx, src/pages/webtoon/WebtoonComment.tsx
- closed #110
- 댓글에 ai모델이 자동 답글해주는 로직 추가
=> #110 댓글에 ai모델이 자동 답글해주는 로직 추가 및 팔로잉, 팔로워 목록 무한불러오기 수정

src/entities/create-id-recom/api/recommendationAPi.ts, src/pages/AIRecommendation/AIRecommendation.tsx
=> 회원가입 로직 api 변경

src/entities/admin/api/types.ts, src/entities/admin/api/userStatsApi.ts, src/entities/admin/api/webtoonStatsApi.ts, src/entities/admin/store/types.ts, src/entities/admin/store/userStatsStore.ts, src/entities/admin/store/webtoonStatsStore.ts, src/pages/admin/stats/UserStats.tsx, src/pages/admin/stats/WebtoonStats.tsx
=> #118 관리자 페이지 통계 연결 초본

src/pages/webtoon/WebtoonDetail.tsx
- closed #116
- 웹툰 상세페이지 보러가는 버튼 추가
=> #116 웹툰 보러가기 버튼 추가

src/entities/admin/api/webtoon.ts, src/entities/admin/model/webtoon.ts, src/entities/admin/store/webtoonStore.ts
#126 fix 웹툰 스토어 파일추가
#126 fix 웹툰 스토어 파일추가
=> #126 웹툰 스토어 파일추가

src/entities/auth/ui/LoginForm.tsx
=> #127 카카오 로그인 기능 추가

src/entities/auth/ui/LoginForm.tsx, src/entities/webtoon/api/api.ts, src/entities/webtoon/api/store.ts, src/pages/webtoon/WebtoonMain.tsx
=> #132 회원 웹툰 추천 리스트 null 처리

src/features/webtoon-character-chat/ui/CharacterChat.tsx, src/features/webtoon-list/ui/WebtoonGridHorizontal.tsx, src/features/webtoon-reviews/ui/CommunityReviews.tsx, src/pages/error/AdminAccessDenied.tsx, src/pages/error/UserAccessDenied.tsx, src/pages/webtoon/WebtoonMain.tsx, src/shared/ui/custom/CustomDropdown.tsx, src/widgets/header/ui/Header.tsx, src/widgets/header/ui/HeaderActions.tsx
=> #134 페이지에 따른 헤더 구현

src/entities/webtoon/ui/HorizontalWebtoonCard.tsx, src/pages/main/Main.tsx, src/pages/webtoon-search-ai/TextBasedRecommendations.tsx, src/pages/webtoon-search/WebtoonSearchResults.tsx, src/pages/webtoon/WebtoonList.tsx, src/pages/webtoon/WebtoonMain.tsx, src/pages/webtoon/WebtoonRecommendations.tsx, src/shared/config/navigation.ts, src/widgets/header/ui/Header.tsx, src/widgets/layout/ui/Layout.tsx
=> #136 메인페이지 서브네비게이션 개선

src/pages/webtoon/WebtoonDetail.tsx
- closed #138
- 웹툰 상세페이지 버튼 추가
=> #138 웹툰 상세페이지에 버튼 기능들 추가(좋아요, 즐겨찾기, 봤어요)

src/shared/config/navigation.ts, src/widgets/header/ui/Header.tsx
=> #140 네비게이션 경로 수정

src/entities/auth/ui/LoginForm.tsx, src/entities/webtoon/api/api.ts, src/entities/webtoon/api/store.ts, src/pages/main/Main.tsx, src/pages/webtoon/WebtoonMain.tsx, src/widgets/header/ui/Header.tsx
=> #142 API 오류 격리 처리 및 메인 페이지 중복 요청 방지

src/entities/auth/api/api.ts, src/entities/auth/ui/LoginForm.tsx, src/pages/auth/Login.tsx
=> #144 로그인 에러 메시지 개선

src/app/global.css, src/entities/auth/ui/LoginForm.tsx, src/index.css, src/pages/auth/Login.tsx, src/widgets/header/ui/Header.tsx, src/widgets/header/ui/HeaderActions.tsx
=> #146 헤더 관리자 페이지 추가 및 스크롤바 이슈 해결

src/entities/webtoon/api/store.ts, src/entities/webtoon/model/types.ts, src/entities/webtoon/ui/WebtoonCard.tsx, src/features/webtoon-list/ui/WebtoonSlider.tsx, src/pages/AIRecommendation/AIRecommendation.tsx, src/pages/auth/Login.tsx, src/pages/auth/signup/Signup.tsx, src/pages/user/mypage/MyProfile.tsx, src/pages/user/userpage/UserProfile.tsx
=> #150 AI 추천 웹툰 카드 개선

src/entities/auth/ui/OAuthRedirect.tsx
=> refactor : oauth2 로그인 쿠키 형식으로 변경
